ALTER TABLE memberroles       DROP FOREIGN KEY memberroles_ibfk_1;
ALTER TABLE memberroles       DROP FOREIGN KEY memberroles_ibfk_2;
ALTER TABLE memberroles       DROP FOREIGN KEY memberroles_ibfk_3;
ALTER TABLE rolepermissions   DROP FOREIGN KEY rolepermissions_ibfk_1;
ALTER TABLE rolepermissions   DROP FOREIGN KEY rolepermissions_ibfk_2;
ALTER TABLE rolepermissions   DROP FOREIGN KEY rolepermissions_ibfk_3;
ALTER TABLE memberpermissions DROP FOREIGN KEY memberpermissions_ibfk_1;
ALTER TABLE memberpermissions DROP FOREIGN KEY memberpermissions_ibfk_2;
ALTER TABLE memberpermissions DROP FOREIGN KEY memberpermissions_ibfk_3;
ALTER TABLE guildsettings     DROP FOREIGN KEY guildsettings_ibfk_1;
ALTER TABLE guildsettings     DROP FOREIGN KEY guildsettings_ibfk_2;
ALTER TABLE permissions       DROP FOREIGN KEY permissions_ibfk_1;
ALTER TABLE roles             DROP FOREIGN KEY roles_ibfk_1;
ALTER TABLE memberguilds      DROP FOREIGN KEY memberguilds_ibfk_1;
ALTER TABLE memberguilds      DROP FOREIGN KEY memberguilds_ibfk_2;

ALTER TABLE memberroles       ADD  FOREIGN KEY (roleid, guildid)       REFERENCES roles(id, guildid)       ON DELETE CASCADE;
ALTER TABLE memberroles       ADD  FOREIGN KEY (memberid)              REFERENCES members(id)              ON DELETE CASCADE;
ALTER TABLE memberroles       ADD  FOREIGN KEY (guildid)               REFERENCES guilds(id)               ON DELETE CASCADE;
ALTER TABLE rolepermissions   ADD  FOREIGN KEY (roleid, guildid)       REFERENCES roles(id, guildid)       ON DELETE CASCADE;
ALTER TABLE rolepermissions   ADD  FOREIGN KEY (permissionid, guildid) REFERENCES permissions(id, guildid) ON DELETE CASCADE;
ALTER TABLE rolepermissions   ADD  FOREIGN KEY (guildid)               REFERENCES guilds(id)               ON DELETE CASCADE;
ALTER TABLE memberpermissions ADD  FOREIGN KEY (permissionid, guildid) REFERENCES permissions(id, guildid) ON DELETE CASCADE;
ALTER TABLE memberpermissions ADD  FOREIGN KEY (memberid)              REFERENCES members(id)              ON DELETE CASCADE;
ALTER TABLE memberpermissions ADD  FOREIGN KEY (guildid)               REFERENCES guilds(id)               ON DELETE CASCADE;
ALTER TABLE guildsettings     ADD  FOREIGN KEY (guildid)               REFERENCES guilds(id)               ON DELETE CASCADE;
ALTER TABLE guildsettings     ADD  FOREIGN KEY (settingid)             REFERENCES settings(id)             ON DELETE CASCADE;
ALTER TABLE permissions       ADD  FOREIGN KEY (guildid)               REFERENCES guilds(id)               ON DELETE CASCADE;
ALTER TABLE roles             ADD  FOREIGN KEY (guildid)               REFERENCES guilds(id)               ON DELETE CASCADE;
ALTER TABLE memberguilds      ADD  FOREIGN KEY (memberid)              REFERENCES members(id)              ON DELETE CASCADE;
ALTER TABLE memberguilds      ADD  FOREIGN KEY (guildid)               REFERENCES guilds(id)               ON DELETE CASCADE;
